### ISSUE TITLE
change cache font size ,font display missing.

### ISSUE THREAD

**Issue by juice-man** [lvgl/lv_lib_freetype#5]
The effect is as follows:
![image](https://user-images.githubusercontent.com/67527595/86989109-4bf41d00-c1cc-11ea-870e-8f162c527c67.png)

I want to get the effect of font deformation,so  I change get_glyph_dsc_cache_cb() code for test ,but partial display is missing.
the code is as follows:ing.
![image](https://user-images.githubusercontent.com/67527595/86988490-e94e5180-c1ca-11ea-96f3-07e13cb58e06.png)

**Comment by kisvegabor** [comment]
Have you changed `line_height` in `lv_freetype_font_init` as well?

**Comment by juice-man** [comment]
that's right, it  does need to change line_height and base_line as well. think you!
