### ISSUE TITLE
Can support 1bpp font display?

### ISSUE THREAD

**Issue by FASTSHIFT** [lvgl/lv_lib_freetype#8]
I tried some modifications, but the font appears to be wrong.I don't use Cache Manager.
![TH8 GJV$CUG}F6%4IB1`J@9](https://user-images.githubusercontent.com/26767803/104588393-3f80dd80-56a3-11eb-9e70-4b76f2ef19b8.png)

![A}~DGGGI6R_DL9`TZNN(GI7](https://user-images.githubusercontent.com/26767803/104587624-2297da80-56a2-11eb-8eac-0f9b221b5343.png)

8bpp mode is displayed correctly.
![B3HP 32E0)7}9}T)2D(CE$T](https://user-images.githubusercontent.com/26767803/104588093-de590a00-56a2-11eb-8f96-495950f0b114.png)

**Comment by kisvegabor** [comment]
Freetype always creates 8bpp output (at least in our case). 

I haven't investigated what other output formats are supported by freetype and whether they are compatible with LVGL.

If you are interested to check it  LVGL reads the bitmaps like this:

```
box width = 3 px, bpp = 4

bitmap= 0x12, 0x34, 0x56
glyph:
1, 2, 3
4, 5, 6
```

Note that, lines are not padded to full bytes.
